abc:
  config: 34566
spring:
  mail:
    from: yrwemail@126.com
    host: smtp.126.com
    password: JFNUVWLUEOYPFIRV
    properties:
      mail:
        smtp:
          port: 587
    username: yrwemail@126.com
