abc:
  config: 34566
spring:
  mail:
    from: javaspring123@126.com
    host: smtp.126.com
    password: XGFFISOSVANFANFS
    properties:
      mail:
        smtp:
          port: 25
    username: yrwemail@126.com
