abc:
  config: 34566
spring:
  mail:
    from: 211569430@qq.com
    host: smtp.qq.com
    password: cqjgucpkwinobihh
    properties:
      mail:
        smtp:
          port: 587
    username: 517309804@qq.com
